# -*- coding: utf-8 -*-
{
    'name': 'CLBCL',
    'version': '2.0.0',
    'summary': 'CLBCL',
    'sequence': -100,
    'description': """CLBCL""",
    'category': 'Tutorials',
    'author': 'Kelvin',
    'maintainer': 'Kelvin',
    'website': 'https://www.odoomates.tech',
    'license': 'AGPL-3',
    'depends': [
        'sale',
        'mail',
        'website_slides',
        'hr',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/slide_data_v12.xml',
        'data/slide_data_v13.xml',
        'data/slide_data_v14.xml',
        'data/slide_data_v15.xml',
        'wizard/create_appointment_view.xml',
        'wizard/search_appointment_view.xml',
        'views/club_view.xml',
        'views/club_area_view.xml',
        'views/sale_order_view.xml',
        'views/hr_employee_view.xml',
        'views/partner_view.xml',
        'views/club_partner_product_view.xml'
    ],
    'demo': [],
    'qweb': [],
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
