from . import club
from . import sale_order
from . import club_partner_product
from . import club_user
from . import user_otp
from . import product_category
from . import product_template
from . import product_product
from . import product_review
from . import res_partner
from . import product_product
from . import voucher
from . import club_friend
from . import province
from . import district
from . import ward
from . import club_booking
from . import club_booking_friend
from . import club_booking_product
from . import club_move
from . import club_move_product
from . import product_bookmark
from . import point
from . import send_gift
from . import send_gift_product
